<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Manage Title'=>'Mcms Manage',
    'Attachment ID' => 'Attachment ID',
    'Upload Ip' => 'Upload ip',
    'Member Id' => 'Member Id',
    'Created Time' => 'Created Time',
    'Md5' => 'md5',
    'File name' => 'file name',
    'File url' => 'file url',
    'File size' => 'file size',
    'File type' => 'file type',
    'Thumb url' => 'Thumb url',
    'Is Photo' => 'is Photo',
    'Title' => 'Title',
    'State' => 'State',
    'Nav ID'=>'Nav ID',
    'Role Id'=>'Role Id',
    'User name' => 'User name',
    'Password' => 'Password',
    'Login ip' => 'Login ip',
    'Login time' => 'Login time',
    'Code' =>  'Code',
    'Is admin' => 'Is admin',
];
